Repository HYF-Class19/agile-development-group-1, pull requests merged in 2022-07, with the labels that each got.

#3 Planning & Project-README
  .gitignore
  README.md
  images/Valeriya.png
  images/bibhasingh.png
  images/elnura.png
  images/galal.png
  images/gopi.png
  images/nashmia.png
  planning/communication-plan.md
  planning/constraints.md
  planning/retrospective.md
  planning/screenshot.jpg
  planning/user-personas.md
Labels: documentation

#6 communication_plan_md_update
  planning/communication-plan.md
Labels: documentation, group

#8 Constraints
  images/constraint.png
  images/internal.png
  images/time.jpg
  images/time.png
  planning/constraints.md
Labels: documentation, group

#11 User persona
  images/userpersona.png
  images/userpersona2.png
  images/userpersona3.png
  planning/user-personas.md
Labels: documentation, group

#9 Design_md
  planning/design.md
Labels: documentation, group

#13 Persona-update
  planning/user-personas.md
Labels: documentation, group

#14 add_third_persona
  planning/user-personas.md
Labels: documentation, group

#19 update image
  images/userpersona.png
Labels: documentation

#20 Design_md
  images/wireframe.png
  planning/design.md
Labels: design

#21 update readme
  README.md
Labels: group

#24 Backlog
  images/agile.jpg
  images/backlog.jpg
  planning/backlog.md
Labels: documentation, group

#23 Backlog
  planning/backlog.md
Labels: group

#25 development-strategy
  planning/development-strategy.md
Labels: documentation, group

#30 Main info
  .cspell.json
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  styles/index.css
Labels: HTML, CSS

#31 Nav_bar
  .gitignore
  .vscode/settings.json
  index.html
  styles/index.css
Labels: HTML, CSS

#34 Header
  images/happy-tree.jpeg
  index.html
  styles/index.css
Labels: HTML, CSS

#36 Retrospective_md
  planning/retrospective.md
Labels: documentation, group

#37 update
  index.html
Labels: HTML, CSS
